name: 'DataTrails SCITT API'
description: 'Register, Get Receipts and Query Feeds from the DataTrails SCITT API'
inputs:
  scitt-client_id:
    description: 'The CLIENT_ID used to access the DataTrails SCITT APIs'
    required: true
  scitt-secret:
    description: 'The SECRET used to access the DataTrails SCITT APIs'
    required: true
  feed:
    description: 'Unique ID for the collection of statements about an artifact'
    required: true
  payload:
    description: 'The payload file to be registered on the SCITT Service (eg: SBOM, Scan Result, Attestation)'
    required: true
  content-type:
    description: 'The payload content type (iana mediaType) to be registered on the SCITT Service (eg: application/spdx+json, application/vnd.cyclonedx+json, Scan Result, Attestation)'
    required: true
  signed-statement-file:
    description: 'File representing the signed SCITT Statement that will be registered on SCITT.'
    required: false
    default: 'signed-statement.cbor'
  receipt-file:
    description: 'The file to save the cbor receipt'
    required: false
    default: 'receipt.cbor'
  digicert-stm-certificate-id:
    description: 'The certificate ID corresponding to the certificate (and signing key) to sign the statement'
    required: true
  digicert-stm-api-key:
    description: 'The API key for DigiCert Software Trust Manager'
    required: true
  digicert-stm-base-uri:
    description: 'The base URI of the DigiCert Software Trust Manager API'
    required: false
    default: 'https://clientauth.demo.one.digicert.com/signingmanager'
  digicert-stm-api-clientauth-p12-b64:
    description: 'The Base64-encoded PKCS #12 file used for client authentication to the DigiCert Software Trust Manager API'
    required: true
  digicert-stm-api-clientauth-password:
    description: 'The password for the PKCS #12 file used for client authentication to the DigiCert Software Trust Manager API'
    required: true
outputs:
  token: # id of output
    description: 'the token used to authenticate'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.scitt-client_id }}
    - ${{ inputs.scitt-secret }}
    - ${{ inputs.feed }}
    - ${{ inputs.payload }}
    - ${{ inputs.content-type }}
    - ${{ inputs.signed-statement-file }}
    - ${{ inputs.receipt-file }}
